// composables/useDmtReceiptPdf.ts
// Generates a single-transaction receipt PDF for the DMT module (Download Receipt / PDF).
import jsPDF from "jspdf";
import { useDmtFormat } from "./useDmtFormat";

export function useDmtReceiptPdf() {
  const { formatCurrency, maskAccount, formatDateTime } = useDmtFormat();

  const downloadReceipt = (txn: any) => {
    const doc = new jsPDF();

    doc.setFontSize(16);
    doc.setTextColor(17, 66, 212);
    doc.text("BucksBox — Money Transfer Receipt", 14, 20);
    doc.setDrawColor(230, 234, 241);
    doc.line(14, 25, 196, 25);

    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42);
    doc.text(formatCurrency(txn.amount), 14, 40);

    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    const rows: [string, string][] = [
      ["Status", txn.status],
      ["Beneficiary", txn.beneficiaryName || "—"],
      ["Bank", txn.bankName || "—"],
      ["Account", txn.accountNumber ? maskAccount(txn.accountNumber) : "—"],
      ["RRN", txn.rrn || "—"],
      ["Bank Reference", txn.bankReference || "—"],
      ["Transaction ID", txn.transactionId || "—"],
      ["Reference ID", txn.refId || "—"],
      ["Remarks", txn.remarks || "—"],
      ["Date & Time", formatDateTime(txn.createdAt)],
    ];

    let y = 55;
    rows.forEach(([k, v]) => {
      doc.setTextColor(100, 116, 139);
      doc.text(k, 14, y);
      doc.setTextColor(15, 23, 42);
      doc.text(String(v), 90, y);
      y += 9;
    });

    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by BucksBox Agent Portal — this is a system-generated receipt.", 14, y + 10);

    doc.save(`BucksBox-DMT-${txn.transactionId || txn.refId || Date.now()}.pdf`);
  };

  return { downloadReceipt };
}
